# Generate descriptor file for CANARGB
# Use this script to avoid duplication and reduce maintenance.

import json
import sys
from sys import argv
from datetime import datetime, timezone
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-v", "--version", help="Firmware version")
args = parser.parse_args()

# default capabilities
moduleName = "CANARGB"
paletteSize = 16
ledActions = 62

now = datetime.now(timezone.utc)
datestring = f"{now.year}{now.month:02}{now.day:02}{now.hour:02}{now.minute:02}"
commandLine = " ".join(argv)

data = {
    "generated": f"Generated by {commandLine}",
    "timestamp": datestring,
    "moduleName": moduleName,
    "tokens": {
      "palette": {
          "defaultNames": {
              "1": "0 : Black / off",
              "2": "1 : Dark grey",
              "3": "2 : Dark red",
              "4": "3 : Dark green",
              "5": "4 : Dark blue",
              "6": "5 : Orange",
              "7": "6 : Dark pink",
              "8": "7 : Dark cyan",
              "9": "8 : Grey",
              "10": "9 : Red",
              "11": "10 : Green",
              "12": "11 : Blue",
              "13": "12 : Yellow",
              "14": "13 : Pink (magenta)",
              "15": "14 : Cyan",
              "16": "15 : White"              
          }
      }  
    },
    "nodeVariables": [
        {
            "displayTitle": f"Palette entry ${{palette {e+1}}}",
            "type": "NodeVariableGroup",
            "groupItems": [
                {
                    "type": "NodeVariableNumber",
                    "nodeVariableIndex": e*3 + 1,
                    "displayTitle": "Red"
                },
                {
                    "type": "NodeVariableNumber",
                    "nodeVariableIndex": e*3 + 2,
                    "displayTitle": "Green"
                },
                {
                    "type": "NodeVariableNumber",
                    "nodeVariableIndex": e*3 + 3,
                    "displayTitle": "Blue"
                }
            ]
        } for e in range(0, paletteSize)
    ] + [
        {
            "type": "NodeVariableSelect",
            "nodeVariableIndex": 49,
            "displayTitle": "Colour order",
            "options": [
                {
                    "label": "RGB",
                    "value": 1
                },
                {
                    "label": "RBG",
                    "value": 2
                },
                {
                    "label": "GRB",
                    "value": 3
                },
                {
                    "label": "GBR",
                    "value": 4
                },
                {
                    "label": "BGR",
                    "value": 5
                },
                {
                    "label": "BRG",
                    "value": 6
                }
            ]
        }
    ],
    "eventVariables": [
        {
            "displayTitle": f"LED Action {action + 1}",
            "type": "EventVariableGroup",
            "groupItems": [
                {
                    "displayTitle": "Action",
                    "type": "EventVariableGroup",
                    "groupItems": [
                        {
                            "displayTitle": "ON event",
                            "type": "EventVariableBitSingle",
                            "eventVariableIndex": action*4 + 1,
                            "bit": 0
                        },
                        {
                            "displayTitle": "Off event",
                            "type": "EventVariableBitSingle",
                            "eventVariableIndex": action*4 + 1,
                            "bit": 1
                        }
                    ]
                },
                {
                    "displayTitle": "Start LED",
                    "type": "EventVariableNumber",
                    "eventVariableIndex": action*4 + 2
                },
                {
                    "displayTitle": "End LED",
                    "type": "EventVariableNumber",
                    "eventVariableIndex": action*4 + 3
                },
                {
                    "type": "EventVariableSelect",
                    "eventVariableIndex": action*4 + 4,
                    "displayTitle": "Flash A",
                    "displaySubTitle": "Palette entry",
                    "bitMask": 0xF,
                    "options": [
                        {"value": p, "label": f"${{palette{p+1}}}"} for p in range(0, paletteSize)
                    ]
                },
                {
                    "type": "EventVariableSelect",
                    "eventVariableIndex": action*4 + 4,
                    "displayTitle": "Flash B",
                    "displaySubTitle": "Palette entry",
                    "bitMask": 0xF0,
                    "options": [
                        {"value": p << 4, "label": f"${{palette{p+1}}}"} for p in range(0, paletteSize)
                    ]
                }
            ]
        } for action in range(0, ledActions)
    ]
}

json.dump(data, sys.stdout, indent=2)
print("")
