# Generate descriptor file for CANARGB
# Use this script to avoid duplication and reduce maintenance.

import json
import sys
from sys import argv
from datetime import datetime, timezone
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-v", "--version", help="Firmware version")
args = parser.parse_args()

# default capabilities
moduleName = "CANARGB"
paletteSize = 16
ledActions = 62

now = datetime.now(timezone.utc)
datestring = f"{now.year}{now.month:02}{now.day:02}{now.hour:02}{now.minute:02}"
commandLine = " ".join(argv)

data = {
    "generated": f"Generated by {commandLine}",
    "timestamp": datestring,
    "moduleName": moduleName,
    "nodeVariables": [
        {
            "displayTitle": f"Palette entry {e}",
            "type": "NodeVariableGroup",
            "groupItems": [
                {
                    "type": "NodeVariableNumber",
                    "nodeVariableIndex": e*3 + 1,
                    "displayTitle": "Red"
                },
                {
                    "type": "NodeVariableNumber",
                    "nodeVariableIndex": e*3 + 2,
                    "displayTitle": "Green"
                },
                {
                    "type": "NodeVariableNumber",
                    "nodeVariableIndex": e*3 + 3,
                    "displayTitle": "Blue"
                }
            ]
        } for e in range(0, paletteSize)
    ] + [
        {
            "type": "NodeVariableSelect",
            "nodeVariableIndex": 49,
            "displayTitle": "Colour order",
            "options": [
                {
                    "label": "RGB",
                    "value": 1
                },
                {
                    "label": "RBG",
                    "value": 2
                },
                {
                    "label": "GRB",
                    "value": 3
                },
                {
                    "label": "GBR",
                    "value": 4
                },
                {
                    "label": "BGR",
                    "value": 5
                },
                {
                    "label": "BRG",
                    "value": 6
                }
            ]
        }
    ],
    "eventVariables": [
        {
            "displayTitle": f"LED Action {action + 1}",
            "type": "EventVariableGroup",
            "groupItems": [
                {
                    "displayTitle": "Action",
                    "type": "EventVariableGroup",
                    "groupItems": [
                        {
                            "displayTitle": "ON event",
                            "type": "EventVariableBitSingle",
                            "eventVariableIndex": action*4 + 1,
                            "bit": 0
                        },
                        {
                            "displayTitle": "Off event",
                            "type": "EventVariableBitSingle",
                            "eventVariableIndex": action*4 + 1,
                            "bit": 1
                        }
                    ]
                },
                {
                    "displayTitle": "Start LED",
                    "type": "EventVariableNumber",
                    "eventVariableIndex": action*4 + 2
                },
                {
                    "displayTitle": "End LED",
                    "type": "EventVariableNumber",
                    "eventVariableIndex": action*4 + 3
                },
                {
                    "type": "EventVariableNumber",
                    "eventVariableIndex": action*4 + 4,
                    "displayTitle": "Flash A",
                    "displaySubTitle": "Palette index",
                    "startBit": 0,
                    "endBit": 3,
                    "max": 15,
                    "min": 0
                },
                {
                    "type": "EventVariableNumber",
                    "eventVariableIndex": action*4 + 4,
                    "displayTitle": "Flash B",
                    "displaySubTitle": "Palette index",
                    "startBit": 4,
                    "endBit": 7,
                    "max": 15,
                    "min": 0
                }
            ]
        } for action in range(0, ledActions)
    ]
}

json.dump(data, sys.stdout, indent=2)
print("")
